name: shelf_response_formatter
version: 0.2.0
description: >
  Simple extensible response formatter which detects appropriate response format
  and serializes data accordingly.
homepage: https://github.com/bwu-dart/shelf_response_formatter
authors:
- Günter Zöchbauer <guenter@gzoechbauer.com>
- Thomas Profelt <tom@octobyte.at>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  shelf: ^0.7.3
  xml: ^3.0.0

dev_dependencies:
  grinder: ^0.8.0
  test: ^1.3.0
